/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesTigerRouteImport } from './routes/games.tiger'
import { Route as GamesSlotsRouteImport } from './routes/games.slots'
import { Route as GamesRouletteRouteImport } from './routes/games.roulette'
import { Route as GamesLuckyRouteImport } from './routes/games.lucky'
import { Route as GamesCrashRouteImport } from './routes/games.crash'
import { Route as GamesCoinRouteImport } from './routes/games.coin'
import { Route as GamesBoxesRouteImport } from './routes/games.boxes'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTigerRoute = GamesTigerRouteImport.update({
  id: '/games/tiger',
  path: '/games/tiger',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlotsRoute = GamesSlotsRouteImport.update({
  id: '/games/slots',
  path: '/games/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouletteRoute = GamesRouletteRouteImport.update({
  id: '/games/roulette',
  path: '/games/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLuckyRoute = GamesLuckyRouteImport.update({
  id: '/games/lucky',
  path: '/games/lucky',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCrashRoute = GamesCrashRouteImport.update({
  id: '/games/crash',
  path: '/games/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCoinRoute = GamesCoinRouteImport.update({
  id: '/games/coin',
  path: '/games/coin',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesBoxesRoute = GamesBoxesRouteImport.update({
  id: '/games/boxes',
  path: '/games/boxes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/games/boxes': typeof GamesBoxesRoute
  '/games/coin': typeof GamesCoinRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/lucky': typeof GamesLuckyRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/tiger': typeof GamesTigerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/games/boxes': typeof GamesBoxesRoute
  '/games/coin': typeof GamesCoinRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/lucky': typeof GamesLuckyRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/tiger': typeof GamesTigerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/games/boxes': typeof GamesBoxesRoute
  '/games/coin': typeof GamesCoinRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/lucky': typeof GamesLuckyRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/tiger': typeof GamesTigerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/games/boxes'
    | '/games/coin'
    | '/games/crash'
    | '/games/lucky'
    | '/games/roulette'
    | '/games/slots'
    | '/games/tiger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/games/boxes'
    | '/games/coin'
    | '/games/crash'
    | '/games/lucky'
    | '/games/roulette'
    | '/games/slots'
    | '/games/tiger'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/games/boxes'
    | '/games/coin'
    | '/games/crash'
    | '/games/lucky'
    | '/games/roulette'
    | '/games/slots'
    | '/games/tiger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MessagesRoute: typeof MessagesRoute
  GamesBoxesRoute: typeof GamesBoxesRoute
  GamesCoinRoute: typeof GamesCoinRoute
  GamesCrashRoute: typeof GamesCrashRoute
  GamesLuckyRoute: typeof GamesLuckyRoute
  GamesRouletteRoute: typeof GamesRouletteRoute
  GamesSlotsRoute: typeof GamesSlotsRoute
  GamesTigerRoute: typeof GamesTigerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tiger': {
      id: '/games/tiger'
      path: '/games/tiger'
      fullPath: '/games/tiger'
      preLoaderRoute: typeof GamesTigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/slots': {
      id: '/games/slots'
      path: '/games/slots'
      fullPath: '/games/slots'
      preLoaderRoute: typeof GamesSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/roulette': {
      id: '/games/roulette'
      path: '/games/roulette'
      fullPath: '/games/roulette'
      preLoaderRoute: typeof GamesRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/lucky': {
      id: '/games/lucky'
      path: '/games/lucky'
      fullPath: '/games/lucky'
      preLoaderRoute: typeof GamesLuckyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/crash': {
      id: '/games/crash'
      path: '/games/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof GamesCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/coin': {
      id: '/games/coin'
      path: '/games/coin'
      fullPath: '/games/coin'
      preLoaderRoute: typeof GamesCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/boxes': {
      id: '/games/boxes'
      path: '/games/boxes'
      fullPath: '/games/boxes'
      preLoaderRoute: typeof GamesBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MessagesRoute: MessagesRoute,
  GamesBoxesRoute: GamesBoxesRoute,
  GamesCoinRoute: GamesCoinRoute,
  GamesCrashRoute: GamesCrashRoute,
  GamesLuckyRoute: GamesLuckyRoute,
  GamesRouletteRoute: GamesRouletteRoute,
  GamesSlotsRoute: GamesSlotsRoute,
  GamesTigerRoute: GamesTigerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
