/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesWarRouteImport } from './routes/games.war'
import { Route as GamesTigerRouteImport } from './routes/games.tiger'
import { Route as GamesSlotsRouteImport } from './routes/games.slots'
import { Route as GamesRouletteRouteImport } from './routes/games.roulette'
import { Route as GamesLuckyRouteImport } from './routes/games.lucky'
import { Route as GamesHorsesRouteImport } from './routes/games.horses'
import { Route as GamesCrashRouteImport } from './routes/games.crash'
import { Route as GamesCoinRouteImport } from './routes/games.coin'
import { Route as GamesBoxesRouteImport } from './routes/games.boxes'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWarRoute = GamesWarRouteImport.update({
  id: '/games/war',
  path: '/games/war',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTigerRoute = GamesTigerRouteImport.update({
  id: '/games/tiger',
  path: '/games/tiger',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlotsRoute = GamesSlotsRouteImport.update({
  id: '/games/slots',
  path: '/games/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouletteRoute = GamesRouletteRouteImport.update({
  id: '/games/roulette',
  path: '/games/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLuckyRoute = GamesLuckyRouteImport.update({
  id: '/games/lucky',
  path: '/games/lucky',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesHorsesRoute = GamesHorsesRouteImport.update({
  id: '/games/horses',
  path: '/games/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCrashRoute = GamesCrashRouteImport.update({
  id: '/games/crash',
  path: '/games/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCoinRoute = GamesCoinRouteImport.update({
  id: '/games/coin',
  path: '/games/coin',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesBoxesRoute = GamesBoxesRouteImport.update({
  id: '/games/boxes',
  path: '/games/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/games/boxes': typeof GamesBoxesRoute
  '/games/coin': typeof GamesCoinRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/horses': typeof GamesHorsesRoute
  '/games/lucky': typeof GamesLuckyRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/tiger': typeof GamesTigerRoute
  '/games/war': typeof GamesWarRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/games/boxes': typeof GamesBoxesRoute
  '/games/coin': typeof GamesCoinRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/horses': typeof GamesHorsesRoute
  '/games/lucky': typeof GamesLuckyRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/tiger': typeof GamesTigerRoute
  '/games/war': typeof GamesWarRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/games/boxes': typeof GamesBoxesRoute
  '/games/coin': typeof GamesCoinRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/horses': typeof GamesHorsesRoute
  '/games/lucky': typeof GamesLuckyRoute
  '/games/roulette': typeof GamesRouletteRoute
  '/games/slots': typeof GamesSlotsRoute
  '/games/tiger': typeof GamesTigerRoute
  '/games/war': typeof GamesWarRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/messages'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/games/boxes'
    | '/games/coin'
    | '/games/crash'
    | '/games/horses'
    | '/games/lucky'
    | '/games/roulette'
    | '/games/slots'
    | '/games/tiger'
    | '/games/war'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/messages'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/games/boxes'
    | '/games/coin'
    | '/games/crash'
    | '/games/horses'
    | '/games/lucky'
    | '/games/roulette'
    | '/games/slots'
    | '/games/tiger'
    | '/games/war'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/messages'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/games/boxes'
    | '/games/coin'
    | '/games/crash'
    | '/games/horses'
    | '/games/lucky'
    | '/games/roulette'
    | '/games/slots'
    | '/games/tiger'
    | '/games/war'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  GamesBoxesRoute: typeof GamesBoxesRoute
  GamesCoinRoute: typeof GamesCoinRoute
  GamesCrashRoute: typeof GamesCrashRoute
  GamesHorsesRoute: typeof GamesHorsesRoute
  GamesLuckyRoute: typeof GamesLuckyRoute
  GamesRouletteRoute: typeof GamesRouletteRoute
  GamesSlotsRoute: typeof GamesSlotsRoute
  GamesTigerRoute: typeof GamesTigerRoute
  GamesWarRoute: typeof GamesWarRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/war': {
      id: '/games/war'
      path: '/games/war'
      fullPath: '/games/war'
      preLoaderRoute: typeof GamesWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tiger': {
      id: '/games/tiger'
      path: '/games/tiger'
      fullPath: '/games/tiger'
      preLoaderRoute: typeof GamesTigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/slots': {
      id: '/games/slots'
      path: '/games/slots'
      fullPath: '/games/slots'
      preLoaderRoute: typeof GamesSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/roulette': {
      id: '/games/roulette'
      path: '/games/roulette'
      fullPath: '/games/roulette'
      preLoaderRoute: typeof GamesRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/lucky': {
      id: '/games/lucky'
      path: '/games/lucky'
      fullPath: '/games/lucky'
      preLoaderRoute: typeof GamesLuckyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/horses': {
      id: '/games/horses'
      path: '/games/horses'
      fullPath: '/games/horses'
      preLoaderRoute: typeof GamesHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/crash': {
      id: '/games/crash'
      path: '/games/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof GamesCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/coin': {
      id: '/games/coin'
      path: '/games/coin'
      fullPath: '/games/coin'
      preLoaderRoute: typeof GamesCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/boxes': {
      id: '/games/boxes'
      path: '/games/boxes'
      fullPath: '/games/boxes'
      preLoaderRoute: typeof GamesBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  GamesBoxesRoute: GamesBoxesRoute,
  GamesCoinRoute: GamesCoinRoute,
  GamesCrashRoute: GamesCrashRoute,
  GamesHorsesRoute: GamesHorsesRoute,
  GamesLuckyRoute: GamesLuckyRoute,
  GamesRouletteRoute: GamesRouletteRoute,
  GamesSlotsRoute: GamesSlotsRoute,
  GamesTigerRoute: GamesTigerRoute,
  GamesWarRoute: GamesWarRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
